/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Conversor;
import controller.Mapeamento;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Memoria;
import model.MemoriaCache;

/**
 *
 * @author Administrator
 */
public class TelaPrincipal extends javax.swing.JFrame{

    Conversor conversor = new Conversor();
    MemoriaCache memoriaCache;//= new MemoriaCache();
    Mapeamento mapeamento = new Mapeamento();
    Memoria memoria = new Memoria();

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getMemoryTrace() {
        return memoryTrace;
    }

    public void setMemoryTrace(JTextField memoryTrace) {
        if (memoryTrace != null) {
            this.memoryTrace = memoryTrace;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha o memory trace");
        }
    }

    public void setConstMemoriaCache() {
        memoriaCache = new MemoriaCache(memoryTrace.getText(),
                Integer.parseInt(palavra.getValue().toString()),
                Integer.parseInt(bloco.getSelectedItem().toString()),
                tipoEntrada.getSelection().getActionCommand(),
                tipoModelo.getSelection().getActionCommand());
    }

    public void limparTabela() {

        memoryTrace.setText("");
        palavra.setValue(1);
        bloco.setSelectedIndex(0);
        tipoEntrada.clearSelection();
        tipoModelo.clearSelection();
        mapeamento = new Mapeamento();
        valorHit.setText("0");
        valorMiss.setText("0");

        for (int i = 4; i >= 1; i--) {
            jTable1.setValueAt(0, 0, i);
            for (int j = 1; j <= 3; j++) {
                jTable1.setValueAt(" ", j, i);
            }

        }

    }

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    public void atualizaContagem() {
        valorHit.setText("" + mapeamento.getCountHit());
        valorMiss.setText("" + mapeamento.getCountMiss());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoModelo = new javax.swing.ButtonGroup();
        tipoEntrada = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        associativaConjunto = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tipoAssociativa = new javax.swing.JRadioButton();
        memoryTrace = new javax.swing.JTextField();
        mapeamentoDireto = new javax.swing.JRadioButton();
        fifo = new javax.swing.JRadioButton();
        lru = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        bloco = new javax.swing.JComboBox();
        palavra = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        valorMiss = new javax.swing.JLabel();
        valorHit = new javax.swing.JLabel();
        passo = new javax.swing.JCheckBox();
        proximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setVisible(true);

        jLabel3.setText("Tamanho do bloco");

        tipoModelo.add(associativaConjunto);
        associativaConjunto.setText("Associativa por Conjunto");
        associativaConjunto.setActionCommand("AssociativaConjunto");
        associativaConjunto.setFocusable(false);
        associativaConjunto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setText("Tamanho da palavra");

        tipoModelo.add(tipoAssociativa);
        tipoAssociativa.setText("Tipo Associativa");
        tipoAssociativa.setActionCommand("TipoAssociativa");
        tipoAssociativa.setFocusable(false);
        tipoAssociativa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tipoAssociativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAssociativaActionPerformed(evt);
            }
        });

        memoryTrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryTraceActionPerformed(evt);
            }
        });

        tipoModelo.add(mapeamentoDireto);
        mapeamentoDireto.setText("Mapeamento Direto");
        mapeamentoDireto.setActionCommand("MapeamentoDireto");
        mapeamentoDireto.setFocusable(false);
        mapeamentoDireto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tipoEntrada.add(fifo);
        fifo.setText("FIFO");
        fifo.setActionCommand("fifo");
        fifo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifoActionPerformed(evt);
            }
        });

        tipoEntrada.add(lru);
        lru.setText("LRU");
        lru.setActionCommand("lru");
        lru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lruActionPerformed(evt);
            }
        });

        jLabel1.setText("Memory trace");

        bloco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "8", "16", "32", "64" }));
        bloco.setEnabled(false);

        palavra.setEnabled(false);
        palavra.setOpaque(false);
        palavra.setValue(1);

        jLabel4.setText("Tipo de entrada");

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bit _Validade", "0", "0", "0", "0"},
                {"Tag", null, null, null, null},
                {"Valor", null, null, null, null},
                {"Num_Inserido", "\"\"", "\"\"", "\"\"", "\"\""}
            },
            new String [] {
                "", "Slot 3", "Slot 2", "Slot 1", "Slot 0"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setMinimumSize(new java.awt.Dimension(100, 60));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel5.setText("Modelo da memória");

        jLabel6.setText("Cache Miss:");

        jLabel7.setText("Cache Hit:");

        valorMiss.setText("0");

        valorHit.setText("0");

        passo.setText("Passo-a-Passo");
        passo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passoActionPerformed(evt);
            }
        });

        proximo.setText("Próximo");
        proximo.setEnabled(false);
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memoryTrace, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(palavra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bloco, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(144, 144, 144)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fifo)
                                    .addComponent(lru)
                                    .addComponent(jLabel4))))
                        .addGap(25, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(mapeamentoDireto)
                            .addComponent(tipoAssociativa)
                            .addComponent(associativaConjunto)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorHit)
                            .addComponent(valorMiss))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passo)
                        .addGap(32, 32, 32)
                        .addComponent(proximo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {associativaConjunto, mapeamentoDireto, tipoAssociativa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(memoryTrace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(palavra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(bloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(fifo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lru))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mapeamentoDireto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoAssociativa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(associativaConjunto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(valorMiss))
                    .addComponent(proximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(valorHit))
                .addGap(29, 29, 29))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {associativaConjunto, mapeamentoDireto, tipoAssociativa});

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoAssociativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAssociativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAssociativaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void memoryTraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryTraceActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_memoryTraceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here      
        try {
            setConstMemoriaCache();

            if (fifo.isSelected()) {
                if (mapeamentoDireto.isSelected()) {
                    mapeamento.mapeamentoDireto(this);
                } else if (tipoAssociativa.isSelected()) {
                    mapeamento.mapeamentoTotalmenteAssociativa(this);
                } else if (associativaConjunto.isSelected()) {
                    mapeamento.mapeamentoAssociativaConjunto(this);
                }

                atualizaContagem();
            } else if (lru.isSelected()) {
                if (tipoAssociativa.isSelected()) {
                    mapeamento.mapeamentoAssociativaConjuntoLRU(this);
                } else if (associativaConjunto.isSelected()) {
                    mapeamento.mapeamentoAssociativaConjuntoLRU(this);
                }
                atualizaContagem();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            limparTabela();
            new TelaPrincipal();
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limparTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lruActionPerformed
        mapeamentoDireto.setEnabled(false);
    }//GEN-LAST:event_lruActionPerformed

    private void fifoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifoActionPerformed
        mapeamentoDireto.setEnabled(true);
    }//GEN-LAST:event_fifoActionPerformed

    private void passoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passoActionPerformed
        if (passo.isSelected()) {
            proximo.setEnabled(true);
        } else {
            proximo.setEnabled(false);
        }
    }//GEN-LAST:event_passoActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        
        
        
    }//GEN-LAST:event_proximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton associativaConjunto;
    private javax.swing.JComboBox bloco;
    private javax.swing.JRadioButton fifo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton lru;
    private javax.swing.JRadioButton mapeamentoDireto;
    private javax.swing.JTextField memoryTrace;
    private javax.swing.JSpinner palavra;
    private javax.swing.JCheckBox passo;
    private javax.swing.JButton proximo;
    private javax.swing.JRadioButton tipoAssociativa;
    private javax.swing.ButtonGroup tipoEntrada;
    private javax.swing.ButtonGroup tipoModelo;
    private javax.swing.JLabel valorHit;
    private javax.swing.JLabel valorMiss;
    // End of variables declaration//GEN-END:variables
}
